[[redirects]]
  from = "/instance"
  to = "http://104.199.127.215/instance"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/accounts"
  to = "http://104.199.127.215/accounts"
  status = 200
  force = true
  headers = {X-From = "Netlify"}